 2019-03-28 19:42:51,312 [P21152/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.7.7 application starting on DESKTOP-TQBND71
 2019-03-28 19:42:51,640 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2019-03-28 19:42:51,672 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 32ms)
 2019-03-28 19:42:51,814 [P21152/D2/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2019-03-28 19:42:51,816 [P21152/D2/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2019-03-28 19:42:51,817 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-03-28 19:42:53,169 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1351ms)
 2019-03-28 19:42:53,169 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2019-03-28 19:42:53,172 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 2ms)
 2019-03-28 19:42:53,315 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-03-28 19:42:53,316 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-03-28 19:42:53,316 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2019-03-28 19:42:53,316 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 0ms)
 2019-03-28 19:42:53,317 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-03-28 19:42:53,317 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-03-28 19:42:53,317 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2019-03-28 19:42:53,319 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 1ms)
 2019-03-28 19:42:53,330 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-03-28 19:42:53,330 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-03-28 19:42:53,330 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2019-03-28 19:42:53,331 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 0ms)
 2019-03-28 19:42:53,331 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-03-28 19:42:53,332 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-03-28 19:42:53,332 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2019-03-28 19:42:53,333 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 1ms)
 2019-03-28 19:42:55,462 [P21152/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2019-03-28 19:42:56,073 [P21152/D2/T1] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2019-03-28 19:42:56,130 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-03-28 19:42:56,130 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-03-28 19:42:56,130 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper
 2019-03-28 19:42:56,131 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper (took 0ms)
 2019-03-28 19:42:57,344 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-03-28 19:42:57,344 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-03-28 19:42:57,344 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2019-03-28 19:42:57,346 [P21152/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 1ms)
 2019-03-28 19:42:58,292 [P21152/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2019-03-28 19:42:58,829 [P21152/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2019-03-28 19:42:58,918 [P21152/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 7860ms)
 2019-03-28 19:43:03,219 [P21152/D2/T12] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost:49447/umbraco (UmbracoModule request)
 2019-03-28 19:43:03,219 [P21152/D2/T11] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost:49447/umbraco (UmbracoModule request)
 2019-03-28 19:43:04,361 [P21152/D2/T11] ERROR SEOChecker.HttpModules.UrlModule - SEOChecker: SEOChecker: Error in HttpModule for url rewriting
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at SEOChecker.Core.Providers.UrlProviders.UrlRewriteProviders.RewriteUrl(String url, UrlRewriteConfig config)
   at SEOChecker.HttpModules.UrlRewriteModule.(Object , EventArgs )
 2019-03-28 19:43:04,843 [P21152/D2/T12] INFO  umbraco.content - Load Xml from file...
 2019-03-28 19:43:04,903 [P21152/D2/T12] INFO  umbraco.content - Loaded Xml from file.
 2019-03-28 19:43:05,038 [P21152/D2/T11] WARN  Umbraco.Web.UmbracoModule - Status code is 404 yet TrySkipIisCustomErrors is false - IIS will take over.
 2019-03-28 19:43:06,363 [P21152/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-03-28 19:43:06,364 [P21152/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-03-28 19:43:06,364 [P21152/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Deploy.IServiceConnector
 2019-03-28 19:43:06,364 [P21152/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Deploy.IServiceConnector (took 0ms)
 2019-03-28 19:44:05,043 [P21152/D2/T11] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2019-03-27 19:44:04
 2019-03-28 20:40:19,047 [P21152/D2/T124] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-03-28 20:40:19,048 [P21152/D2/T124] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-03-28 20:40:19,048 [P21152/D2/T124] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2019-03-28 20:40:19,049 [P21152/D2/T124] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 1ms)
 2019-03-28 20:40:19,252 [P21152/D2/T129] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-03-28 20:40:19,252 [P21152/D2/T129] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-03-28 20:40:19,252 [P21152/D2/T129] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IAction
 2019-03-28 20:40:19,253 [P21152/D2/T129] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IAction (took 0ms)
 2019-03-28 20:40:28,619 [P21152/D2/T127] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username superadmin@nexthome.com from IP address ::1
 2019-03-28 20:40:28,619 [P21152/D2/T127] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: superadmin@nexthome.com logged in from IP address ::1
 2019-03-28 20:40:29,712 [P21152/D2/T127] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-03-28 20:40:29,712 [P21152/D2/T127] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-03-28 20:40:29,712 [P21152/D2/T127] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2019-03-28 20:40:29,712 [P21152/D2/T127] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2019-03-28 20:40:29,715 [P21152/D2/T127] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-03-28 20:40:29,716 [P21152/D2/T127] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-03-28 20:40:29,716 [P21152/D2/T127] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree
 2019-03-28 20:40:29,716 [P21152/D2/T127] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree (took 0ms)
 2019-03-28 20:40:29,847 [P21152/D2/T125] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-03-28 20:40:29,847 [P21152/D2/T125] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-03-28 20:40:29,848 [P21152/D2/T125] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ITree
 2019-03-28 20:40:29,848 [P21152/D2/T125] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ITree (took 0ms)
 2019-03-28 20:40:29,947 [P21152/D2/T126] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-03-28 20:40:29,947 [P21152/D2/T126] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-03-28 20:40:29,947 [P21152/D2/T126] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication
 2019-03-28 20:40:29,948 [P21152/D2/T126] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication (took 0ms)
 2019-03-28 20:49:25,778 [P21152/D2/T109] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field multiPicker
 2019-03-28 20:49:25,779 [P21152/D2/T109] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field onlyImages
 2019-03-28 20:49:25,779 [P21152/D2/T116] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field default
 2019-03-28 20:49:25,782 [P21152/D2/T109] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field disableFolderSelect
 2019-03-28 20:49:25,784 [P21152/D2/T109] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field startNodeId
 2019-03-28 20:49:25,820 [P21152/D2/T117] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-03-28 20:49:25,874 [P21152/D2/T109] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field multiPicker
 2019-03-28 20:49:25,874 [P21152/D2/T109] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field onlyImages
 2019-03-28 20:49:25,874 [P21152/D2/T109] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field disableFolderSelect
 2019-03-28 20:49:25,874 [P21152/D2/T109] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field startNodeId
 2019-03-28 20:49:25,893 [P21152/D2/T116] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field default
 2019-03-28 20:49:25,906 [P21152/D2/T111] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-03-28 20:49:25,929 [P21152/D2/T118] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-03-28 20:49:26,003 [P21152/D2/T109] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-03-28 20:49:26,003 [P21152/D2/T116] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-03-28 20:49:26,011 [P21152/D2/T112] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-03-28 20:49:26,031 [P21152/D2/T18] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-03-28 20:49:26,044 [P21152/D2/T110] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-03-28 21:00:00,176 [P21152/D2/T114] INFO  Umbraco.Core.Logging.OwinLogger - Event Id: 0, state: User logged will be logged out due to timeout: superadmin@nexthome.com, IP Address: ::1
 2019-03-28 22:58:38,764 [P21152/D2/T59] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt failed for username its\mahmoud.yousef from IP address ::1
 2019-03-28 22:58:45,488 [P21152/D2/T167] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt failed for username its\mahmoud.yousef from IP address ::1
 2019-03-28 22:59:01,346 [P21152/D2/T59] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username superadmin@nexthome.com from IP address ::1
 2019-03-28 22:59:01,346 [P21152/D2/T59] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: superadmin@nexthome.com logged in from IP address ::1
 2019-03-28 23:18:36,969 [P21152/D2/T87] INFO  Umbraco.Core.Logging.OwinLogger - Event Id: 0, state: User logged will be logged out due to timeout: superadmin@nexthome.com, IP Address: ::1
 2019-03-28 23:44:05,136 [P21152/D2/T93] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2019-03-27 23:44:05
 2019-03-28 23:46:36,021 [P21152/D2/T93] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username superadmin@nexthome.com from IP address ::1
 2019-03-28 23:46:36,021 [P21152/D2/T93] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: superadmin@nexthome.com logged in from IP address ::1
 2019-03-28 23:47:12,564 [P21152/D2/T104] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-03-28 23:47:12,564 [P21152/D2/T104] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-03-28 23:47:12,564 [P21152/D2/T104] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Editors.IEditorValidator
 2019-03-28 23:47:12,576 [P21152/D2/T104] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Editors.IEditorValidator (took 8ms)
 2019-03-28 23:47:12,808 [P21152/D2/T104] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-03-28 23:47:12,808 [P21152/D2/T104] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-03-28 23:47:12,808 [P21152/D2/T104] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ICacheRefresher
 2019-03-28 23:47:12,808 [P21152/D2/T104] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ICacheRefresher (took 0ms)
 2019-03-28 23:47:12,840 [P21152/D2/T104] INFO  SEOChecker.Core.Helpers.CacheRefresher - SEO Checker cache cleared by ICacheRefresher Event
 2019-03-28 23:47:51,188 [P21152/D2/T93] ERROR Umbraco.Web.Editors.ContentController - Unhandled controller exception occurred
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<GetModelAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<>c__DisplayClass5_0.<BindModel>b__1(Task`1 x)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.BindModel(HttpActionContext actionContext, ModelBindingContext bindingContext)
   at System.Web.Http.ModelBinding.ModelBinderParameterBinding.ExecuteBindingAsync(ModelMetadataProvider metadataProvider, HttpActionContext actionContext, CancellationToken cancellationToken)
   at System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<GetModelAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<>c__DisplayClass5_0.<BindModel>b__1(Task`1 x)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<GetModelAsync>d__7.MoveNext()<---
<---

 2019-03-28 23:47:57,745 [P21152/D2/T98] ERROR Umbraco.Web.Editors.ContentController - Unhandled controller exception occurred
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<GetModelAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<>c__DisplayClass5_0.<BindModel>b__1(Task`1 x)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.BindModel(HttpActionContext actionContext, ModelBindingContext bindingContext)
   at System.Web.Http.ModelBinding.ModelBinderParameterBinding.ExecuteBindingAsync(ModelMetadataProvider metadataProvider, HttpActionContext actionContext, CancellationToken cancellationToken)
   at System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<GetModelAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<>c__DisplayClass5_0.<BindModel>b__1(Task`1 x)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<GetModelAsync>d__7.MoveNext()<---
<---

 2019-03-28 23:48:22,201 [P21152/D2/T93] ERROR Umbraco.Web.Editors.ContentController - Unhandled controller exception occurred
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<GetModelAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<>c__DisplayClass5_0.<BindModel>b__1(Task`1 x)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.BindModel(HttpActionContext actionContext, ModelBindingContext bindingContext)
   at System.Web.Http.ModelBinding.ModelBinderParameterBinding.ExecuteBindingAsync(ModelMetadataProvider metadataProvider, HttpActionContext actionContext, CancellationToken cancellationToken)
   at System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<GetModelAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<>c__DisplayClass5_0.<BindModel>b__1(Task`1 x)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at Umbraco.Web.WebApi.Binders.ContentItemBaseBinder`2.<GetModelAsync>d__7.MoveNext()<---
<---

 2019-03-28 23:48:33,960 [P21152/D2/T93] WARN  Umbraco.Core.PropertyEditors.PropertyValueEditor - The value  cannot be converted to the type Integer
 2019-03-28 23:48:33,992 [P21152/D2/T93] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'الرئيسية' with Id '1069' has been published.
 2019-03-28 23:48:38,345 [P21152/D2/T93] INFO  umbraco.content - Save Xml to file...
 2019-03-28 23:48:38,401 [P21152/D2/T93] INFO  umbraco.content - Saved Xml to file.
 2019-03-28 23:48:42,987 [P21152/D2/T93] WARN  Umbraco.Core.PropertyEditors.PropertyValueEditor - The value  cannot be converted to the type Integer
 2019-03-28 23:48:42,999 [P21152/D2/T93] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'الرئيسية' with Id '1069' has been published.
 2019-03-28 23:48:47,129 [P21152/D2/T100] INFO  umbraco.content - Save Xml to file...
 2019-03-28 23:48:47,133 [P21152/D2/T100] INFO  umbraco.content - Saved Xml to file.
 2019-03-28 23:48:47,656 [P21152/D2/T98] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field default
 2019-03-28 23:48:47,660 [P21152/D2/T93] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-03-28 23:48:47,660 [P21152/D2/T100] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field multiPicker
 2019-03-28 23:48:47,660 [P21152/D2/T100] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field onlyImages
 2019-03-28 23:48:47,664 [P21152/D2/T100] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field disableFolderSelect
 2019-03-28 23:48:47,664 [P21152/D2/T100] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field startNodeId
 2019-03-28 23:48:47,744 [P21152/D2/T92] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-03-28 23:48:47,764 [P21152/D2/T91] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-03-28 23:48:47,776 [P21152/D2/T95] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-03-28 23:48:47,796 [P21152/D2/T104] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-03-28 23:48:47,800 [P21152/D2/T90] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-03-28 23:48:47,812 [P21152/D2/T98] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-03-28 23:48:47,856 [P21152/D2/T96] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-03-28 23:48:47,900 [P21152/D2/T98] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field default
 2019-03-28 23:48:47,904 [P21152/D2/T92] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field multiPicker
 2019-03-28 23:48:47,904 [P21152/D2/T92] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field onlyImages
 2019-03-28 23:48:47,904 [P21152/D2/T92] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field disableFolderSelect
 2019-03-28 23:48:47,908 [P21152/D2/T92] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field startNodeId
